const router = require('express').Router();
const rateLimit = require('express-rate-limit');
const { auth } = require('../middleware/auth');
const { requireCsrf, requireTrustedOrigin, issueCsrf } = require('../middleware/csrf');
const c = require('../controllers/auth.controller');
const security = require('../controllers/account-security.controller');
const limiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: 'draft-8', legacyHeaders: false, skipSuccessfulRequests: true });
router.get('/csrf', issueCsrf);
router.post('/login', requireTrustedOrigin, limiter, requireCsrf, c.login);
router.get('/me', auth, c.me);
router.post('/legal-acceptance', requireTrustedOrigin, auth, requireCsrf, c.acceptLegal);
router.post('/logout', requireTrustedOrigin, requireCsrf, auth, c.logout);
router.post('/forgot-password', requireTrustedOrigin, limiter, requireCsrf, security.forgotPassword);
router.post('/reset-password', requireTrustedOrigin, limiter, requireCsrf, security.resetPassword);
router.post('/password', requireTrustedOrigin, requireCsrf, auth, limiter, security.changePassword);
router.get('/security', auth, security.status);
router.post('/preferences', requireTrustedOrigin, requireCsrf, auth, security.preferences);
router.post('/mfa/setup', requireTrustedOrigin, requireCsrf, auth, limiter, security.setupMfa);
router.post('/mfa/confirm', requireTrustedOrigin, requireCsrf, auth, limiter, security.confirmMfa);
router.post('/mfa/disable', requireTrustedOrigin, requireCsrf, auth, limiter, security.disableMfa);
module.exports = router;
